### ISSUE TITLE
Add T1/T2 description to docs

### ISSUE THREAD

**Issue by eefaye** [digitalearthafrica/deafrica-docs#26]
**Context:** Landsat data is segregated into Tier 1 and Tier 2 "collections" (not to be confused with the LS Collection 1 / Collection 2 nomenclature). Some DE Africa Landsat data services use T2 only, while some include both T1 and T2.
**Applies to:** all Landsat data and services as it is tiered at the surface reflectance, which is an input source for surface temperature

**Actions to resolve this issue:**
 - Add a separate descriptor page explaining the difference between T1 and T2 (can keep it short, link to the official Landsat website description of this) and why it is an important piece of metadata
 - Update all the Landsat data/service specs pages to include a row in the table to indicate whether T1 data is included or not (or if it can optionally be loaded, as is with `lsX_sr` using the `collection_category` argument)

**Comment by eefaye** [comment]
https://www.usgs.gov/media/videos/landsat-collections-what-are-tiers

https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/main/Tools/deafrica_tools/datahandling.py#L391
Looks like the default is "load Tier 1 (T1) data only". It is confusing that the label is called `collection_category` but that does refer to Tiers, not to Collection1 / Collection 2.

I'm thinking the article could be linked from the [data specs landing page](https://docs.digitalearthafrica.org/en/latest/data_specs/index.html) as it applies to all our Landsat services, but there are some restructurings going on there so we don't need to lock it in yet.

**Comment by vikineema** [comment]
PR merged https://github.com/digitalearthafrica/deafrica-docs/pull/49.
