### ISSUE TITLE
Remove all training.deafrica links

### ISSUE THREAD

**Issue by eefaye** [digitalearthafrica/deafrica-docs#38]
For instance, often included as:

> For instructions on how to connect to OWS, see this tutorial.

This is common in the data_specs subpages 

Links to training.digitalearthafrica.org should be removed and linked to the Knowledge Base or Learning Platform instead, as required.

**Comment by andrewdhicks** [comment]
Only link to `training` left is from the GeoMAD spec page, pointinng to the Geomedian_widget https://training.digitalearthafrica.org/en/latest/Geomedian_widget.html

Should it go to the sandbox-notebooks repo, on the GeoMAD dataset page?

**Comment by eefaye** [comment]
Ah, good spot. I've been wondering this myself and haven't figured it out yet (and kept putting it off). Might try and come to an actionable conclusion on Wednesday. What do you think - where should it go?

**Comment by andrewdhicks** [comment]
Closed by #54
